version: '3'
services:
  app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - '80:3000'
      - '443:3001'
    links:
      - mongo
    volumes:
      - './public/data:/public/data'
      - '/etc/letsencrypt:/etc/letsencrypt'
#     volumes:
#       -  ~/OneDrive/Documents/code/WebSurvey/public:/public
#       -  ~/OneDrive/Documents/code/WebSurvey/views:/views
  mongo:
    container_name: mongo-app
    image: arm64v8/mongo
    volumes:
      - './db:/data/db'
